# Generated by Django 3.2.13 on 2022-05-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.IntegerField(choices=[(0, 'procesory'), (1, 'karty graficzne'), (2, 'płyty główne'), (3, 'pamięci RAM'), (4, 'dyski SSD')]),
        ),
    ]
