# Generated by Django 3.2.13 on 2022-05-28 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop_app', '0002_alter_category_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.IntegerField(choices=[(0, 'CPU'), (1, 'GPU'), (2, 'Motherboards')]),
        ),
    ]
