# Generated by Django 3.2.13 on 2022-06-06 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webshop_app', '0010_alter_product_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_picture',
        ),
    ]
