# Generated by Django 3.2.13 on 2022-06-19 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webshop_app', '0016_remove_cart_total_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
