# Generated by Django 3.2.13 on 2022-06-19 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webshop_app', '0017_delete_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cancelled',
        ),
        migrations.RemoveField(
            model_name='order',
            name='confirmed',
        ),
        migrations.RemoveField(
            model_name='order',
            name='note',
        ),
    ]
