# Generated by Django 3.2.13 on 2022-06-19 13:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop_app', '0021_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='text_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
